apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: steuritos-data
  namespace: steuritos
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 100Mi
